version: "3.9"

services:
  renew_x_auto_pardon:
    build: .
    container_name: renew_x_auto_pardon
    environment:
      RENEW_URL: ${RENEW_URL}
      PASSWORD: ${PASSWORD}
      CRON_EXPR: "0 8 * * *"  # 每天早上 8 点运行一次
    restart: unless-stopped
