version: "3.8"

services:
  login:
    build: .
    container_name: login-script
    environment:
      - RENEW_URL=${RENEW_URL}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./app:/app  # 将当前目录挂载到容器中的 /app 目录
    restart: unless-stopped
    entrypoint: ["xvfb-run", "--auto-servernum", "--server-args='-screen 0 1024x768x24'", "python", "allow.py"]
    # Cron 配置：每三天运行一次
    cron:
      schedule: "0 0 */3 * *"
      command: ["xvfb-run", "--auto-servernum", "--server-args='-screen 0 1024x768x24'", "python", "allow.py"]
