version: "3.9"

services:
  renew_x_auto_pardon:
    image: onlinemo/renew_x_auto_pardon
    container_name: renew_x_auto_pardon
    environment:
      - RENEW_URL=https://你的地址
      - PASSWORD=你的密码
      - CRON_EXPR=0 8 * * *  # 每天早上 8 点运行一次
    command: >
      sh -c "echo \"$CRON_EXPR xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python /app/allow.py\" | supercronic /dev/stdin"
    restart: unless-stopped
