version: '3.8'

services:
  renew_x_auto_pardon:
    build: .
    container_name: renew_x_auto_pardon
    env_file:
      - .env
    command: >
      sh -c "echo \"$CRON_EXPR xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python allow.py\" | supercronic -"
    restart: unless-stopped
